### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sritala** [Melimet/TowerDefence#2]
(Ladattu 26.4.2019 23.03)

- Metodit ovat sopivan pituisia sekä metodit ovat nimetty kuvattu niille sopivilla nimillä.
- Koodi näyttää kaikin puolin siistiltä! Jäsennykset ovat aika lailla tehtyjä ja plussaa, että javadocilla on selitetty metodeja auki.
- Luokat noudattavat aikalailla single responsibilityä ja ovat nimetty ja jaettu pakkauksiin järkevästi. 
- Ei päällekkäisyyttä, joten metodit ja luokat hoitavat omia asioitaan. 
- Silmään pisti, että testiluokissa on jonkun verran gettereitä, joita laatuvaatimusten mukaan ei tarvitse testata.
- Ehdotuksena peliin voisi rakentaa sulkemismahdollisuuden jos haluaa lopettaa pelin kesken.

**Comment by Melimet** [comment]
Kiitos palautteesta!
